version: "3.9"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbt_demo
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/ # Exécution automatique des scripts SQL

  dbt:
    build:
      context: .
    container_name: dbt_container
    volumes:
      - .:/usr/app
    depends_on:
      - db
    environment:
      DBT_PROFILES_DIR: /usr/app
      DBT_TARGET_PATH: target/
    entrypoint: ["/bin/bash", "-c", "dbt deps && tail -f /dev/null"]

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
